services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.local
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db

  vite:
    image: node:25.4.0-alpine3.22
    working_dir: /var/www/
    command: sh -lc "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
      - e_museu_node_modules:/var/www/node_modules
    depends_on:
      - db

  web:
    image: nginx:mainline-alpine3.22-perl
    ports:
      - "${WEB_SERVER_PORT_LOCAL}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/local_prod-local/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0-debian # Image used in staging & production
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
        - "${PHP_MYADMIN_PORT_LOCAL}:80"
    environment:
        PMA_HOST: db
        PMA_PORT: ${DB_PORT}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}

volumes:
  e_museu_node_modules:
