services:
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
      target: app
    working_dir: /var/www
    depends_on:
      - db-staging
    networks:
      - e_museu_staging

  web-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
      target: web
    depends_on:
      - app-staging
    networks:
      - e_museu_staging
    expose:
      - "80"

  db-staging:
    image: mysql:8.0.43-debian
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_staging_data:/var/lib/mysql
    networks:
      - e_museu_staging

volumes:
  mysql_staging_data:

networks:
  e_museu_staging:
    driver: bridge
