services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod-local
      target: app
    working_dir: /var/www/
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod-local
      target: web
    ports:
      - "${WEB_SERVER_PORT_PROD_LOCAL}:80"
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0-debian # Image used in staging & production
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
