services:
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
      target: app
    working_dir: /var/www
    depends_on:
      - db-staging

  web-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
      target: web
    depends_on:
      - app-staging
    expose:
      - "80"

  db-staging:
    image: mysql:8.0.43-debian
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      # /root/databases/staging/mysql_data_staging (root's home directory when opening console)
      - /root/databases/staging/mysql_data_staging:/var/lib/mysql
