services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod-local
      target: app
    working_dir: /var/www/
    networks:
      - e_museu_prod_local_network
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod-local
      target: web
    ports:
      - "${WEB_SERVER_PORT_PROD_LOCAL}:80"
    depends_on:
      - app
    networks:
      - e_museu_prod_local_network

  db:
    image: mysql:8.0.43-debian
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - e_museu_prod_local_network 

networks:
  e_museu_prod_local_network:
    driver: bridge
